### ISSUE TITLE
Import fails after upgrade to Ember 2.12

### ISSUE THREAD

**Issue by gabrielgrant** [ciena-blueplanet/ember-dagre#77]
This was working well before updating to Ember 2.12, but after the upgrade, I'm getting an import error:

```
ember.debug.js:18008 Error: Could not find module `ciena-dagre` imported from `pachdash/components/p-network`
```

**Comment by sandersky** [comment]
@gabrielgrant I believe the fix is to do the same thing as in this [PR](https://github.com/ciena-blueplanet/ember-lodash-shim/pull/48). I don't have time to make a PR for this right now but if you want to make one I'll happily review it and merge it.

**Comment by gabrielgrant** [comment]
Ah, good catch. Thanks for the pointer (and the quick reply). I'll try that out and get a PR together

**Comment by gabrielgrant** [comment]
Yup, that seems to fix it. Just submitted a PR...now on to submit the same fix to [ciena-graphlib](https://github.com/ciena-blueplanet/ember-graphlib) :P

**Comment by gabrielgrant** [comment]
No longer needed as of ember-cli 2.12.1: https://github.com/ember-cli/ember-cli/pull/6884
